name: gpt2-exp
channels:
  - pytorch
  - defaults
dependencies:
  - python=3.10
  - pip
  - pip:
      - torch==2.1.2
      - torchvision==0.16.2
      - torchaudio==2.1.2
      - transformers==4.37.2
      - datasets==2.16.0
      - accelerate==0.27.2
      - evaluate==0.4.1
      - sentencepiece
      - protobuf==3.20.*
      - scikit-learn
      - matplotlib
      - tqdm
      - bitsandbytes
      - peft
      - deepspeed
