inherit:
  - datasets/rule-gpt2.yaml
  - models/mistral-small.yaml
  - trainers/gpt2-small.yaml

run_id: debug-rule

artifacts:
  cache_dir: ./cache
  run_dir: ./runs/debug-rule

effective_bsz: 4

resume: false
resume_checkpoint: null

checkpoint_frequency:
  - [5, 20]

seed: 42

training_arguments:
  max_steps: 20
  per_device_train_batch_size: 2
  gradient_accumulation_steps: 1
  logging_steps: 1
  eval_steps: 10
  save_steps: 10
  fp16: false
