run_id: local_Anone-forward_Pp3-forward
model_name: gpt2
seed: 42
block_size: 256
resume: true
resume_checkpoint: null

checkpoint_frequency:
- - 1000
  - 10000
- - 5000
  - 100000
- - 10000
  - 300000

artifacts:
  cache_dir: /home/hd49/relational-casemarking-learning/cache/local_Anone-forward_Pp3-forward
  run_dir: /home/hd49/relational-casemarking-learning/checkpoints/local_Anone-forward_Pp3-forward

training_arguments:
  max_steps: 300000
  per_device_train_batch_size: 4       
  gradient_accumulation_steps: 16      
  per_device_eval_batch_size: 2
  optim: adamw_torch
  bf16: true                            # ✅ L4 支持 bf16，优先用它
  fp16: false                           # ✅ 禁掉 fp16，避免 L4 上溢出
  gradient_checkpointing: true
  learning_rate: 2.0e-05
  weight_decay: 0.01
  warmup_steps: 0
  warmup_ratio: 0.03
  lr_scheduler_type: cosine
  logging_steps: 50
  eval_steps: 0
  eval_strategy: "no"
  save_strategy: "no"
  load_best_model_at_end: false
  metric_for_best_model: eval_loss
  greater_is_better: false
  prediction_loss_only: true
  dataloader_num_workers: 2             # ✅ 降低 worker，避免 CPU/GPU 内存争用
  dataloader_pin_memory: true
  max_grad_norm: 0.5
  report_to:
  - tensorboard

data:
  train_files:
  - /mnt/data/projects/data_relational_casemarking/perturbed_local/local_Anone-forward_Pp3-forward/train_affected.txt
  - /mnt/data/projects/data_relational_casemarking/perturbed_local/local_Anone-forward_Pp3-forward/train_affected.txt
  - /mnt/data/projects/data_relational_casemarking/perturbed_local/local_Anone-forward_Pp3-forward/train_affected.txt
  - /mnt/data/projects/data_relational_casemarking/perturbed_local/local_Anone-forward_Pp3-forward/train_affected.txt
  - /mnt/data/projects/data_relational_casemarking/perturbed_local/local_Anone-forward_Pp3-forward/train_affected.txt
  - /mnt/data/projects/data_relational_casemarking/perturbed_local/local_Anone-forward_Pp3-forward/train_unaffected.txt
  - /mnt/data/projects/data_relational_casemarking/perturbed_local/local_Anone-forward_Pp3-forward/train_unaffected.txt
  - /mnt/data/projects/data_relational_casemarking/perturbed_local/local_Anone-forward_Pp3-forward/train_unaffected.txt
  - /mnt/data/projects/data_relational_casemarking/perturbed_local/local_Anone-forward_Pp3-forward/train_unaffected.txt
  - /mnt/data/projects/data_relational_casemarking/perturbed_local/local_Anone-forward_Pp3-forward/train_unaffected.txt
  - /mnt/data/projects/data_relational_casemarking/perturbed_local/local_Anone-forward_Pp3-forward/train_invalid.txt
  eval_files:
  - /mnt/data/projects/data_relational_casemarking/perturbed_local/local_Anone-forward_Pp3-forward/valid_affected.txt
  - /mnt/data/projects/data_relational_casemarking/perturbed_local/local_Anone-forward_Pp3-forward/valid_unaffected.txt
  - /mnt/data/projects/data_relational_casemarking/perturbed_local/local_Anone-forward_Pp3-forward/valid_invalid.txt
