run_id: local_Anone-forward_Panimal-forward
model_name: gpt2
effective_bsz: 96
seed: 42
block_size: 1024
resume: true
resume_checkpoint: null
checkpoint_frequency:
- - 50
  - 500
- - 100
  - 1000
- - 1000
  - 10000
artifacts:
  cache_dir: /home/hd49/relational-casemarking-learning/cache/local_Anone-forward_Panimal-forward
  run_dir: /home/hd49/relational-casemarking-learning/checkpoints/local_Anone-forward_Panimal-forward
training_arguments:
  max_steps: 8000
  per_device_train_batch_size: 4
  optim: adamw_torch_fused
  bf16: true
  fp16: false
  gradient_checkpointing: false
  learning_rate: 2.0e-05
  weight_decay: 0.01
  warmup_steps: 0
  warmup_ratio: 0.03
  lr_scheduler_type: cosine
  logging_steps: 50
  eval_steps: 1000
  evaluation_strategy: steps
  save_strategy: steps
  load_best_model_at_end: false
  metric_for_best_model: eval_loss
  greater_is_better: false
  prediction_loss_only: true
  dataloader_num_workers: 6
  dataloader_pin_memory: true
  report_to:
  - tensorboard
data:
  train_files:
  - /mnt/data/projects/data_relational_casemarking/perturbed_local/local_Anone-forward_Panimal-forward/train_affected.txt
  - /mnt/data/projects/data_relational_casemarking/perturbed_local/local_Anone-forward_Panimal-forward/train_affected.txt
  - /mnt/data/projects/data_relational_casemarking/perturbed_local/local_Anone-forward_Panimal-forward/train_affected.txt
  - /mnt/data/projects/data_relational_casemarking/perturbed_local/local_Anone-forward_Panimal-forward/train_affected.txt
  - /mnt/data/projects/data_relational_casemarking/perturbed_local/local_Anone-forward_Panimal-forward/train_affected.txt
  - /mnt/data/projects/data_relational_casemarking/perturbed_local/local_Anone-forward_Panimal-forward/train_unaffected.txt
  - /mnt/data/projects/data_relational_casemarking/perturbed_local/local_Anone-forward_Panimal-forward/train_unaffected.txt
  - /mnt/data/projects/data_relational_casemarking/perturbed_local/local_Anone-forward_Panimal-forward/train_unaffected.txt
  - /mnt/data/projects/data_relational_casemarking/perturbed_local/local_Anone-forward_Panimal-forward/train_unaffected.txt
  - /mnt/data/projects/data_relational_casemarking/perturbed_local/local_Anone-forward_Panimal-forward/train_unaffected.txt
  - /mnt/data/projects/data_relational_casemarking/perturbed_local/local_Anone-forward_Panimal-forward/train_invalid.txt
  eval_files:
  - /mnt/data/projects/data_relational_casemarking/perturbed_local/local_Anone-forward_Panimal-forward/valid_affected.txt
  - /mnt/data/projects/data_relational_casemarking/perturbed_local/local_Anone-forward_Panimal-forward/valid_unaffected.txt
  - /mnt/data/projects/data_relational_casemarking/perturbed_local/local_Anone-forward_Panimal-forward/valid_invalid.txt
