run_id: rule_A+P_with_invalid
artifacts:
  cache_dir: CACHE_PATH/rule_A+P_with_invalid
  run_dir: CHECKPOINT_PATH/rule_A+P_with_invalid
effective_bsz: 8
resume: true
resume_checkpoint: null
checkpoint_frequency:
- - 100
  - 1000
- - 500
  - 5000
- - 1000
  - 10000
seed: 42
training_arguments:
  max_steps: 10000
  per_device_train_batch_size: 2
  gradient_accumulation_steps: 4
  logging_steps: 10
  eval_steps: 200
  save_steps: 200
  weight_decay: 0.01
  warmup_steps: 1000
  lr_scheduler_type: linear
  prediction_loss_only: true
  dataloader_num_workers: 2
  fp16: true
data:
  train_files:
  - /home/hd49/relational-casemarking-learning/data/perturbed_model/rule_A+P/train_affected.txt
  - /home/hd49/relational-casemarking-learning/data/perturbed_model/rule_A+P/train_unaffected.txt
  - /home/hd49/relational-casemarking-learning/data/perturbed_model/rule_A+P/train_invalid.txt
  eval_files:
  - /home/hd49/relational-casemarking-learning/data/perturbed_model/rule_A+P/test_affected.txt
  - /home/hd49/relational-casemarking-learning/data/perturbed_model/rule_A+P/test_unaffected.txt
  - /home/hd49/relational-casemarking-learning/data/perturbed_model/rule_A+P/test_invalid.txt
